name: esp_softap_provisioning
description: Provisioning ESP32 modules with SoftAP
version: 1.0.1
homepage: https://github.com/ShrapnelDSP/esp_softap_provisioning/tree/shrapnel

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  protobuf: ^3.1.0
  cryptography: ^2.0.1
  logger: ^2.0.2+1
  string_validator: ^1.0.2
  http: ^1.1.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.25.7