name: esp_softap_provisioning
description: A Flutter plugin for provisioning ESP32 modules with SoftAP
version: 1.0.1
homepage: https://github.com/omert08/esp_softap_provisioning

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^3.1.0
  cryptography: ^2.0.1
  logger: ^2.0.2+1
  string_validator: ^1.0.2
  http: ^1.1.0
  collection: ^1.15.0
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.omert.esp_softap_provisioning
        pluginClass: EspSoftapProvisioningPlugin
      ios:
        pluginClass: EspSoftapProvisioningPlugin